config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: "tasks#index"
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :destroy, :update]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks do
    collection do
      post :confirm

      resources :users, only: [:new, :create, :show]
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :task_limit_on, presence: true
  validates :task_status, presence: true
  validates :priority, presence: true

  belongs_to :user, optional: true
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  enum task_status: { 未着手: 0, 着手中: 1, 完了: 2 }
  enum priority: { 選択して下さい: 0, 低: 1, 中: 2, 高: 3 }

  scope :get_by_title, -> (title) { where('title LIKE ?', "%#{title}%")}
  scope :get_by_task_status, -> (task_status) { where(task_status: task_status)}
  # scope :unfinished, -> { where(done: false) }
  # scope :get_by_priority, -> (priority) { where(priority: priority)}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:title].present? && params[:task_status].present?
      @tasks = current_user.tasks.get_by_title(params[:title]).get_by_task_status(params[:task_status]).page(params[:page]).per(5)
    elsif params[:title].present?
      @tasks = current_user.tasks.get_by_title(params[:title]).page(params[:page]).per(5)
    elsif params[:task_status].present?
      @tasks = current_user.tasks.get_by_task_status(params[:task_status]).page(params[:page]).per(5)
    elsif params[:sort_expired]
      @tasks = current_user.tasks.order(task_limit_on: "DESC").page(params[:page]).per(5)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority:"DESC").page(params[:page]).per(5)
    else
      @tasks = current_user.tasks.order(id: "DESC").page(params[:page]).per(5)
    end

    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
      # 入力フォームを再描画します。
      render :new
      # end
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  # def confirm
  #   @task = Task.new(task_params)
  #   render :new if @task.invalid?
  # end

  private
  def task_params
    params.require(:task).permit(:title, :task_limit_on, :task_status, :priority, { label_ids: [] })
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      # confirm_tasks_path
      tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ,url: choose_new_or_edit) do |form| %>
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= @task.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="task_title">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>
<div class="task_limit_on">
  <%= form.label :task_limit_on, "期限" %>
  <%= raw sprintf(
  form.date_select(
  :task_limit_on,
  use_month_numbers: true,
  start_year:        2020,
  end_year:          (Time.now.year + 20),
  default:           Date.new(2020, 1, 1),
  date_separator:    '%s'), # 年月日区切りをそれぞれ指定
  '年 ', '月 ') + '日'
  %>
</div>
<div class="task_status">
  <%= form.label :task_status, "ステータス" %>
  <%= form.select :task_status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], include_blank: "選択して下さい" %>
</div>
<div class="priority">
  <%= form.label :priority, "優先順位" %>
  <%= form.select :priority, [["低", "低"], ["中", "中"], ["高", "高"]], include_blank: "選択して下さい" %>
</div>
<div class="field">
  <%= form.label :name, "ラベル" %>
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
</div>
<%= form.submit %>
<% end %>
<%= link_to 'タスク一覧画面に戻る', tasks_path, class: "btn btn-primary btn-lg" %>

app/views/tasks/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @task.title %></p>
  <p>本文:<%= @task.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
 <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<div>
  <%= form_with(url:tasks_path,local: true,method: :get) do |form| %>
  <%= form.label :title,'タイトル検索' %>
  <%= form.text_field :title,value: params[:title] %>
  <%= form.label :task_status,'ステータス検索' %>
  <%= form.select :task_status,Task.task_statuses.keys, selected: params[:task_status],include_blank:"選択して下さい" %>
  <%= form.label :name,'ラベル検索' %>
  <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: "ラベルを選択する" }) %>
  <%= form.submit 'Search' %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>期限</th>
      <th>ステータス</th>
      <th>優先順位</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.task_limit_on %></td>
      <td><%= task.task_status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to '詳細を確認する', task_path(task.id), class: "btn btn-outline-primary" %></td>
      <td><%= link_to "タスクを編集する", edit_task_path(task.id), class: "btn btn-outline-warning", data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to 'タスクを削除する', task_path(task.id), class: "btn btn-outline-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      <td>
        <% task.labels.each do |label| %>
          <%= label.name %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true"), class: "btn btn-primary btn-lg" %>
<%= link_to "優先順位が高い順にソートする", tasks_path(sort_priority: "true"), class: "btn btn-primary btn-lg" %>

<br>
<%= link_to 'タスクを作成する', new_task_path, class: "btn btn-dark btn-lg" %>
<%= link_to '管理者画面/ユーザー一覧へ', admin_users_path, class: "btn btn-dark btn-lg" %>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
 <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タイトル: <%= @task.title %></p>
<p>期限: <%= @task.task_limit_on %></p>
<p>ステイタス: <%= @task.task_status %></p>
<p>優先順位: <%= @task.priority %></p>

<%= link_to 'タスク一覧画面に戻る', tasks_path, class: "btn btn-primary btn-lg" %>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>