config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: "tasks#index"
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :destroy, :update]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks do
    collection do
      post :confirm

      resources :users, only: [:new, :create, :show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, {presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }}

  before_validation { email.downcase! }
  before_destroy :admin_zero
  before_update  :admin_authorization

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, foreign_key: :user_id, dependent: :destroy
  # enum admin: { user: 0, admin: 1 }


  private

  def admin_authorization

  end

  def admin_zero
    if User.where(admin: true).length == 1 && self.admin?
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.includes(:tasks)
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除しました。"
    else
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除できません。"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def if_not_admin
    redirect_to root_path, notice: "管理者以外アクセスできません" unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action:logged_in_user,only:[:new,:create]
  before_action :ensure_current_user, only:[:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    # if @user == current_user
    # else
    #   redirect_to root_path, notice: "他者のページアクセスできません"
    # end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def ensure_current_user
    if current_user.admin == false
      if @current_user.id != params[:id].to_i
        redirect_to root_path
      end
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
<div class="user_title">
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box :admin %>
</div>
<%= f.submit "実行"%>
<%= link_to '管理者画面/ユーザー一覧へ', admin_users_path, class: "btn btn-dark btn-sm" %>
<% end %>

app/views/admin/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/admin/users/edit.html.erb
<h2>ユーザー情報を編集する</h2>
 <%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>管理画面/ユーザー一覧</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>ユーザー名</th>
    <th>管理者</th>
    <th>タスク数</th>
  </tr>
  </thead>
  <tbody>
<%  @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user_path(user.id) %></td>
    <td><%= user.admin %></td>
    <td><%= user.tasks.count  %>
    <td><%= link_to 'ユーザー情報詳細', admin_user_path(user.id), class: "btn btn-outline-primary" %></td>
    <td><%= link_to "ユーザー情報編集", edit_admin_user_path(user.id), class: "btn btn-outline-warning" %></td>
    <td><%= link_to 'ユーザー情報削除', admin_user_path(user.id), class: "btn btn-outline-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
<%= link_to '新規ユーザー登録', new_admin_user_path, class: "btn btn-dark btn-lg", id: "admin-users_index-new_user_link"  %>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box :admin %>
  <%= f.submit "アカウント作成" %>
<% end %>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細画面</h1>
<table class="table table-striped">
  <thead>

    <tr>
      <th>ユーザー名 :<%= @user.name %></th>
      <th>メールアドレス :<%= @user.email %></th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <th>タイトル</th>
    <th>期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>
  </tbody>
   <tfoot>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.task_limit_on %></td>
      <td><%= task.task_status %></td>
      <td><%= task.priority %></td>
    </tr>
    <% end %>
  </tfoot>
</table>
<%= link_to '管理者画面/ユーザー一覧へ', admin_users_path, class: "btn btn-dark btn-lg" %>

app/views/admin/users/update.html.erb
<h2>ユーザー情報を編集する</h2>
 <%= render 'form' %>